Task 1: A DatFrame has been created using the students data as provided earlier from dictionary. students_df is the DataFrame name created.

In [2]:
import pandas as pd
# Create a pandas DataFrame using the student data provided below
data={
    "StudentID" :[101,102,103,104,105,106,107,108,109,110],
    "Name":["Alice","Bob","Charlie","Diana","Ethan","Fiona","George","Hannah","Ivan","Julia"],
    "Age":[20,21,19,22,20,21,23,19,22,20],
    "Marks":[88,75,92,65,78,85,70,95,60,80],
    "Grade" :["A","B","A","C","B","A","B","A","C","B"]
}

students_df=pd.DataFrame(data)
print(students_df)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

Task 2:Using to_csv function the students_df dataframe is copied into students.csv file and saved them with message.

In [3]:
# Save the DataFrame as a CSV file named students.csv

students_df.to_csv("students.csv",index=False)
print("Saved as students.csv")

Saved as students.csv

Task 3:Using read_csv function the students.csv file is loaded into another dataframe named df.

In [4]:
# Reload students.csv into a new DataFrame

df =pd.read_csv("students.csv")
print("CSV is loaded Successfully")

CSV is loaded Successfully

Task 4: Using df.head(3) function to diplay the first 3 rows of the dataframe.

In [5]:
# Display the first 3 rows using df.head(3)
df.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

Task 5: Using df.describe(),Statistical summary is being displayed on the integer columns,if required we can select specific column and then perform this describe function.

In [6]:
# Display the statistical summary using df.describe()
df.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

Task 6: It prints the DataFrame’s shape, column data types, and a summary of its structure using .info().

In [7]:
#Explore the data further using df.shape, df.dtypes, and df.info()
print("\n\n df.shape")
print(df.shape)

print("\n df.dtypes")
print(df.dtypes)


print("\n df.info()")
print(df.info())

 df.shape
(10, 5)

 df.dtypes
StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

 df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None